server:
  port: ${PORT:8080}
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

security:
  basic:
    enabled: true
  require-ssl: true

spring:
  application:
    name: KafkaViewer
  datasource:
    schema: "classpath:/schema/schema.sql"
#    data: "classpath:/schema/data.sql"

  http:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  thymeleaf:
    cache: false
    enabled: true
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: HTML
    encoding: UTF-8
    check-template-location: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

## Various App Configs
app:
  name: Kafka Web View
  uploadPath: "./uploads"
  companyName:
  companyAddress:
  baseUrl:
  systemEmail:
