
# General
server:

  ## What port to run the service on.
  port: 8080

  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    mbeanregistry:
      enabled: true

  servlet:
    session:
      ## User sessions should not be persistent across service restarts by default.
      persistent: false
      ## User login session timeout after 1 hour (3600 seconds)
      timeout: 3600


# Spring
spring:

  application:
    name: Kafka Webview

  datasource:
    url: "jdbc:h2:file:./data/db"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    locations: "classpath:schema/migration/{vendor}"
    baselineOnMigrate: true

  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB

  thymeleaf:
    cache: false
    enabled: true
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: HTML
    encoding: UTF-8
    check-template-location: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true


# Spring Actuator - Global
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  ## Disable LDAP by default
  health:
    ldap:
      enabled: false

# Spring Actuator - Info endpoint
info:
  app:
    name: ${spring.application.name}


# Kafka WebView custom
app:

  ## Application name
  name: Kafka WebView

  ## TODO: add a description to this configuration
  uploadPath: "./data/uploads"

  ## Should be unique to your installation.
  ## This key will be used for symmetric encryption of JKS/TrustStore secrets if you configure any SSL enabled Kafka clusters.
  key: "SuperSecretKey"

  ## Defines a prefix prepended to the Id of all consumers.
  consumerIdPrefix: "KafkaWebViewConsumer"

  ## Enable multi-threaded consumer support
  ## The previous single-threaded implementation is still available by setting this property to false.
  ## The previous implementation along with this property will be removed in future release.
  multiThreadedConsumer: true

  ## Sets upper limit on the number of concurrent consumers (non-websocket) supported.
  maxConcurrentWebConsumers: 32

  ## Sets upper limit on the number of concurrent web socket consumers supported.
  maxConcurrentWebSocketConsumers: 64

  ## Require SSL
  requireSsl: false

  ## User authentication options
  user:
    ## Require user authentication
    ## Setting to false will disable login requirement.
    enabled: true

    ## Ldap auth settings
    ## Optional: if you want to use LDAP for user authentication instead of locally defined users.
    ldap:
      ## Disabled by default.
      enabled: false

      ## URL/Hostname for your LDAP server
      url: "ldap://localhost:63182/dc=example,dc=org"

      ## Example values defined below, adjust as needed.
      ## How to find user records
      userDnPattern: "uid={0},ou=people"

      ## The attribute in which the password is stored.
      passwordAttribute: "userPassword"

      ## Where to find user group membership
      groupSearchBase: "ou=groups"
      groupRoleAttribute: "cn"
      groupSearchFilter: "(uniqueMember={0})"

      ## How passwords are validated, must implement PasswordEncoder interface
      passwordEncoderClass: "org.springframework.security.crypto.password.LdapShaPasswordEncoder"

      ## Comma separated list of groups. A user which is a member of this group will be granted
      ## administrator access to Kafka WebView.
      adminGroups: "ADMINGROUP1,ADMINGROUP2"

      ## Comma separated list of groups. A user which is a member of this group will be granted
      ## standard user level access to Kafka WebView.
      userGroups: "USERGROUP1,USERGROUP2"

      ## Any user who is not a member of at least one of the above groups will be denied access
      ## to Kafka WebView.

      ## If LDAP does not allow anonymous access, define the user/password to connect using.
      ## If not required, leave both fields empty
      bindUser: "cn=ManagementUser"
      bindUserPassword: "password-here"
