
# General
server:

  servlet:
    session:
      persistent: true


# Spring
spring:

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2


# Kafka WebView custom
app:

  user:
    enabled: true
    ## Development server Ldap auth settings
    ldap:
      enabled: false
      url: "ldap://localhost:55555/dc=springframework,dc=org"
      adminGroups: "MANAGERS"
      userGroups: "DEVELOPERS"
